export let productos = [
  {
      "imagen": "https://www.ktronix.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-197529985793-001.jpg?context=bWFzdGVyfGltYWdlc3wyMDc0NzR8aW1hZ2UvanBlZ3xhR1F6TDJneFppOHhNemt5TXpneU5EZzVNems0TWk4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TVRrM05USTVPVGcxTnprelh6QXdNUzVxY0djfGE1ZWQ1YWY0NjNjYmE1ZDUyZTIyY2I5OWJhNjZkODlmMTk3MDM3YWM2M2IwYjUzNjQ1YzU1NjA1ZjJiN2QyMzM",
      "nombre": "Laptop Gaming Modelo A",
      "descripcion": "Una potente laptop gaming con procesador de alta velocidad y gráficos impresionantes.",
      "precio": 1099.99,
      "descuento": false,
      "numeroEstrellas": 4,
      "precioDescuento": 0,
      "categoria": "Laptop",
      "numeroReviews": 25,
      "id": 1
  },
  {
      "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_852127-MCO52213486516_102022-F.webp",
      "nombre": "Teclado Mecánico RGB",
      "descripcion": "Teclado mecánico con retroiluminación RGB personalizable para una experiencia de juego inmersiva.",
      "precio": 89.99,
      "descuento": true,
      "numeroEstrellas": 4.2,
      "precioDescuento": 69.99,
      "categoria": "Complementos",
      "numeroReviews": 18,
      "id": 2
  },
  {
      "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_995599-MCO69058238316_042023-F.webp",
      "nombre": "Monitor Gaming 27 pulgadas",
      "descripcion": "Monitor de alta frecuencia de actualización y resolución para jugadores exigentes.",
      "precio": 349.99,
      "descuento": true,
      "numeroEstrellas": 4.6,
      "precioDescuento": 299.99,
      "categoria": "Monitor",
      "numeroReviews": 30,
      "id": 3
  },
  {
      "imagen": "https://i.linio.com/p/3c05933fd86a5915dfba97b35c11afad-product.webp",
      "nombre": "Tarjeta Gráfica GTX 3080",
      "descripcion": "Una tarjeta gráfica potente que ofrece un rendimiento de juego de última generación.",
      "precio": 799.99,
      "descuento": false,
      "numeroEstrellas": 4.8,
      "precioDescuento": 0,
      "categoria": "Partes PC",
      "numeroReviews": 40,
      "id": 4
  },
  {
      "imagen": "https://i.linio.com/p/f09aec3f09ae91525a13f6fcc738c915-product.webp",
      "nombre": "Auriculares Gaming Inalámbricos",
      "descripcion": "Auriculares inalámbricos con sonido envolvente para una experiencia de juego inmersiva.",
      "precio": 129.99,
      "descuento": false,
      "numeroEstrellas": 3,
      "precioDescuento": 0,
      "categoria": "Complementos",
      "numeroReviews": 22,
      "id": 5
  },
  {
      "imagen": "https://i.ebayimg.com/images/g/SsMAAOSwhDBfGF4w/s-l500.jpg",
      "nombre": "Silla Gaming Ergonómica",
      "descripcion": "Una silla ergonómica diseñada para sesiones de juego largas y cómodas.",
      "precio": 199.99,
      "descuento": true,
      "numeroEstrellas": 3,
      "precioDescuento": 169.99,
      "categoria": "Complementos",
      "numeroReviews": 28,
      "id": 6
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/VdcAAOSwFq5kzjWF/s-l500.png",
    "nombre": "PC Gamer de Alto Rendimiento",
    "descripcion": "Una PC de alto rendimiento con procesador de última generación y tarjeta gráfica potente.",
    "precio": 1699.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 15,
    "id": 7
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_760989-MCO71275609389_082023-F.webp",
    "nombre": "Mouse Gaming con RGB",
    "descripcion": "Un mouse gaming con iluminación RGB personalizable y sensor de alta precisión.",
    "precio": 49.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 39.99,
    "categoria": "Complementos",
    "numeroReviews": 12,
    "id": 8
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_897288-MLA45260403198_032021-F.webp",
    "nombre": "Disco Duro SSD de 1TB",
    "descripcion": "Un disco duro SSD de gran capacidad para mejorar la velocidad y capacidad de almacenamiento de tu PC.",
    "precio": 129.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 23,
    "id": 9
  },
  {
    "imagen": "https://www.lenovo.com/medias/25198557406-G34w-30-20220726014906.png?context=bWFzdGVyfHJvb3R8MTE5NTUzfGltYWdlL3BuZ3xoMDYvaGU5LzE1Mjc3NjUyMzc3NjMwLnBuZ3w5NjU4ODhiNDAzYmYzMjdjNmYyNTAwMzQ3MzQzOTI3ZDU0YWFkNzI2ZWQ5NjE2MzM2Y2EzMmI3MDE5YTdmMjQ3",
    "nombre": "Monitor Curvo 32 pulgadas",
    "descripcion": "Un monitor curvo de gran tamaño con una inmersión visual impresionante para tus juegos.",
    "precio": 449.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 399.99,
    "categoria": "Monitor",
    "numeroReviews": 35,
    "id": 10
  },
  {
    "imagen": "producto52.jpg",
    "nombre": "Auriculares con Cancelación de Ruido",
    "descripcion": "Auriculares con tecnología de cancelación de ruido para una experiencia de juego sin distracciones.",
    "precio": 149.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Audio",
    "numeroReviews": 20,
    "id": 11
  },
  {
    "imagen": "producto53.jpg",
    "nombre": "Teclado Mecánico Compacto",
    "descripcion": "Un teclado mecánico compacto y portátil ideal para juegos en movimiento.",
    "precio": 79.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 69.99,
    "categoria": "Complementos",
    "numeroReviews": 14,
    "id": 12
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_722629-MLU71495580321_092023-F.webp",
    "nombre": "Laptop Gaming Modelo B",
    "descripcion": "Una laptop gaming de gama media con gráficos sólidos y rendimiento confiable.",
    "precio": 899.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 799.99,
    "categoria": "Laptop",
    "numeroReviews": 26,
    "id": 13
  },
  {
    "imagen": "producto55.jpg",
    "nombre": "Silla Gaming Estilo Racing",
    "descripcion": "Una silla estilo racing con diseño deportivo y soporte lumbar ajustable.",
    "precio": 169.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 19,
    "id": 14
  },
  {
    "imagen": "producto56.jpg",
    "nombre": "Placa Base para Gaming",
    "descripcion": "Una placa base diseñada para jugadores con múltiples puertos y capacidades de overclocking.",
    "precio": 129.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 109.99,
    "categoria": "Partes PC",
    "numeroReviews": 27,
    "id": 15
  },
  {
    "imagen": "producto57.jpg",
    "nombre": "Mousepad Gaming Extra Grande",
    "descripcion": "Un mousepad extra grande para jugadores que necesitan mucho espacio para el ratón.",
    "precio": 19.99,
    "descuento": false,
    "numeroEstrellas": 4.0,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 16,
    "id": 16
  },
  {
    "imagen": "producto58.jpg",
    "nombre": "Memoria RAM DDR4 16GB",
    "descripcion": "Memoria RAM de alto rendimiento para mejorar la velocidad de tu PC.",
    "precio": 79.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 69.99,
    "categoria": "Partes PC",
    "numeroReviews": 22,
    "id": 17
  },
  {
    "imagen": "producto59.jpg",
    "nombre": "Sistema de Refrigeración Líquida",
    "descripcion": "Un sistema de refrigeración líquida eficiente para mantener tu PC fresco durante largas sesiones de juego.",
    "precio": 89.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 25,
    "id": 18
  },
  {
    "imagen": "producto60.jpg",
    "nombre": "Mochila para Portátil Gamer",
    "descripcion": "Una mochila resistente y espaciosa diseñada para transportar tu laptop gaming y accesorios.",
    "precio": 49.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 39.99,
    "categoria": "Complementos",
    "numeroReviews": 13,
    "id": 19
  },

  {
    "imagen": "https://i.linio.com/p/eaeadecee1384c5721708aaa59c75c8c-product.webp",
    "nombre": "Laptop Gamer Modelo C",
    "descripcion": "Una laptop gamer de alta gama con pantalla de alta frecuencia de actualización y gráficos excepcionales.",
    "precio": 1499.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 32,
    "id": 20
  },
  {
    "imagen": "https://i.linio.com/p/15abd3b04a64890369c931caa0697165-product.webp",
    "nombre": "Laptop Ultradelgada",
    "descripcion": "Una laptop ultradelgada y liviana ideal para jugadores en movimiento.",
    "precio": 999.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 899.99,
    "categoria": "Laptop",
    "numeroReviews": 22,
    "id": 21
  },
  {
    "imagen": "https://www.alkosto.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-4711121614538-001.jpg?context=bWFzdGVyfGltYWdlc3wyMTc1NDB8aW1hZ2UvanBlZ3xhR05oTDJoak15OHhNemczTmpBNU1UYzBPRE00TWk4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TkRjeE1URXlNVFl4TkRVek9GOHdNREV1YW5CbnwwZTcwMGE5Yjg2NmY2MzBlZGI3ZDYxYzI0Zjg0N2E2NzJkNDc4NzFiZDY5MWU3ZDU0NzcxMThiNzAzMjA4MTZh",
    "nombre": "Laptop de Gama Media",
    "descripcion": "Una laptop de gama media con rendimiento sólido y gráficos decentes para juegos.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 18,
    "id": 22
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_651093-MLU71266572179_082023-F.webp",
    "nombre": "Laptop Híbrida 2 en 1",
    "descripcion": "Una laptop híbrida con capacidad de convertirse en tableta para una versatilidad máxima.",
    "precio": 1199.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 1099.99,
    "categoria": "Laptop",
    "numeroReviews": 19,
    "id": 23
  },
  {
    "imagen": "https://www.alkosto.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-196800901132-001.jpg?context=bWFzdGVyfGltYWdlc3wyNTI1OTR8aW1hZ2UvanBlZ3xhREEzTDJnMk9DOHhNelUwTkRJNU1UY3lPVFF6T0M4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TVRrMk9EQXdPVEF4TVRNeVh6QXdNUzVxY0djfDZmMmNhOTY1YWJlNTI1NjgwMjVlN2M1ZTQ4MjY1NjEyNzFkNzg5ZjdmNDY5YzUyYzUwNTUwMjVlMmYwMTkxYWI",
    "nombre": "Laptop de Edición de Video",
    "descripcion": "Una laptop potente diseñada para la edición de video y juegos de alto rendimiento.",
    "precio": 1799.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 28,
    "id": 24
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_962719-MLA53042953925_122022-F.webp",
    "nombre": "Laptop de Gama Alta",
    "descripcion": "Una laptop de gama alta con especificaciones de vanguardia para los jugadores más exigentes.",
    "precio": 2199.99,
    "descuento": true,
    "numeroEstrellas": 4.9,
    "precioDescuento": 1999.99,
    "categoria": "Laptop",
    "numeroReviews": 35,
    "id": 25
  },
  {
    "imagen": "https://i.linio.com/p/b926eebd64bc5897c92db5ccbf5270a6-product.webp",
    "nombre": "Laptop para Diseñadores Gráficos",
    "descripcion": "Una laptop diseñada para diseñadores gráficos y artistas digitales con pantalla de alta resolución.",
    "precio": 1399.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 29,
    "id": 26
  },
  {
    "imagen": "https://puntoscolombia.vtexassets.com/arquivos/ids/23516250-800-auto?v=638227265535030000&width=800&height=auto&aspect=true",
    "nombre": "Laptop Económica",
    "descripcion": "Una laptop económica ideal para jugadores principiantes con un presupuesto ajustado.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.1,
    "precioDescuento": 549.99,
    "categoria": "Laptop",
    "numeroReviews": 15,
    "id": 27
  },
  {
    "imagen": "https://i.linio.com/p/28a79e27ac8d318946ada27b9bae438c-product.webp",
    "nombre": "Laptop para Streaming",
    "descripcion": "Una laptop optimizada para transmisiones en vivo y contenido de video en línea.",
    "precio": 1299.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 1199.99,
    "categoria": "Laptop",
    "numeroReviews": 27,
    "id": 28
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_987978-MCO53373547477_012023-F.webp",
    "nombre": "Laptop para Programadores",
    "descripcion": "Una laptop diseñada para programadores y desarrolladores con rendimiento de alta velocidad.",
    "precio": 1099.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 25,
    "id": 29
  },
  {
    "imagen": "producto71.jpg",
    "nombre": "Monitor Curvo 34 pulgadas Ultra Ancho",
    "descripcion": "Un monitor curvo ultrapanorámico para una experiencia visual inmersiva como ninguna otra.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 38,
    "id": 30
  },
  {
    "imagen": "producto72.jpg",
    "nombre": "Monitor 4K HDR 27 pulgadas",
    "descripcion": "Un monitor 4K de alta resolución con soporte HDR para colores vibrantes y claridad impresionante.",
    "precio": 499.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 449.99,
    "categoria": "Monitor",
    "numeroReviews": 29,
    "id": 31
  },
  {
    "imagen": "producto73.jpg",
    "nombre": "Monitor para Diseñadores Gráficos",
    "descripcion": "Un monitor de alta precisión diseñado para profesionales de diseño gráfico y edición de fotos.",
    "precio": 749.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 32,
    "id": 32
  },
  {
    "imagen": "producto74.jpg",
    "nombre": "Monitor 144Hz para Gaming",
    "descripcion": "Un monitor de alta frecuencia de actualización para jugadores competitivos que buscan la máxima suavidad.",
    "precio": 349.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 299.99,
    "categoria": "Monitor",
    "numeroReviews": 25,
    "id": 33
  },
  {
    "imagen": "producto75.jpg",
    "nombre": "Monitor Táctil de 22 pulgadas",
    "descripcion": "Un monitor táctil para interacciones intuitivas y aplicaciones educativas y creativas.",
    "precio": 199.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 18,
    "id": 34
  },
  {
    "imagen": "producto76.jpg",
    "nombre": "Monitor 32 pulgadas 4K Curvo",
    "descripcion": "Un monitor curvo de gran tamaño con resolución 4K para una experiencia visual asombrosa.",
    "precio": 699.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 599.99,
    "categoria": "Monitor",
    "numeroReviews": 28,
    "id": 35
  },
  {
    "imagen": "producto77.jpg",
    "nombre": "Monitor Gaming 24 pulgadas",
    "descripcion": "Un monitor gaming de 24 pulgadas con tiempo de respuesta ultrarrápido para jugadores competitivos.",
    "precio": 249.99,
    "descuento": false,
    "numeroEstrellas": 4.5,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 23,
    "id": 36
  },
  {
    "imagen": "producto78.jpg",
    "nombre": "Monitor Curvo 27 pulgadas QHD",
    "descripcion": "Un monitor curvo de resolución QHD para una experiencia visual envolvente y nítida.",
    "precio": 399.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 349.99,
    "categoria": "Monitor",
    "numeroReviews": 21,
    "id": 37
  },
  {
    "imagen": "producto79.jpg",
    "nombre": "Monitor 23 pulgadas Full HD",
    "descripcion": "Un monitor Full HD de 23 pulgadas ideal para tareas de oficina y entretenimiento en casa.",
    "precio": 179.99,
    "descuento": false,
    "numeroEstrellas": 4.0,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 15,
    "id": 38
  },
  {
    "imagen": "producto80.jpg",
    "nombre": "Monitor 27 pulgadas 4K IPS",
    "descripcion": "Un monitor de 27 pulgadas con panel IPS y resolución 4K para una calidad de imagen excepcional.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 549.99,
    "categoria": "Monitor",
    "numeroReviews": 20,
    "id": 39
  },
  {
    "imagen": "producto81.jpg",
    "nombre": "PC Gaming de Alta Gama",
    "descripcion": "Una PC gaming de alta gama con procesador de última generación y tarjeta gráfica de alto rendimiento.",
    "precio": 1999.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 36,
    "id": 40
  },
  {
    "imagen": "producto82.jpg",
    "nombre": "Mini PC Compacto",
    "descripcion": "Un mini PC compacto y potente ideal para el entretenimiento en el hogar y tareas de oficina.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 549.99,
    "categoria": "PC",
    "numeroReviews": 19,
    "id": 41
  },
  {
    "imagen": "producto83.jpg",
    "nombre": "PC de Oficina Profesional",
    "descripcion": "Una PC de oficina de alto rendimiento para tareas profesionales y multitarea eficiente.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.5,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 27,
    "id": 42
  },
  {
    "imagen": "producto84.jpg",
    "nombre": "PC Todo en Uno",
    "descripcion": "Un PC todo en uno con pantalla táctil y diseño elegante para espacios de trabajo modernos.",
    "precio": 1299.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 1199.99,
    "categoria": "PC",
    "numeroReviews": 32,
    "id": 43
  },
  {
    "imagen": "producto85.jpg",
    "nombre": "PC de Juegos Compacto",
    "descripcion": "Un PC compacto diseñado para juegos de alto rendimiento en espacios reducidos.",
    "precio": 899.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 24,
    "id": 44
  },
  {
    "imagen": "producto86.jpg",
    "nombre": "PC de Diseño Gráfico",
    "descripcion": "Una PC de alto rendimiento diseñada para diseñadores gráficos y artistas digitales.",
    "precio": 1499.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 1399.99,
    "categoria": "PC",
    "numeroReviews": 30,
    "id": 45
  },
  {
    "imagen": "producto87.jpg",
    "nombre": "PC de Oficina Económica",
    "descripcion": "Una PC económica diseñada para tareas de oficina y navegación en Internet.",
    "precio": 499.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 17,
    "id": 46
  },
  {
    "imagen": "producto88.jpg",
    "nombre": "PC de Juegos de Gama Media",
    "descripcion": "Un PC de juegos de gama media con un equilibrio entre rendimiento y presupuesto.",
    "precio": 1199.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 1099.99,
    "categoria": "PC",
    "numeroReviews": 28,
    "id": 47
  },
  {
    "imagen": "producto89.jpg",
    "nombre": "PC de Trabajo en Casa",
    "descripcion": "Una PC diseñada para el trabajo en casa y la teleconferencia con alta calidad de video y audio.",
    "precio": 699.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 26,
    "id": 48
  },
  {
    "imagen": "producto90.jpg",
    "nombre": "PC de Juegos de Gama Baja",
    "descripcion": "Un PC de juegos de gama baja para juegos básicos y tareas de navegación.",
    "precio": 499.99,
    "descuento": true,
    "numeroEstrellas": 4.0,
    "precioDescuento": 449.99,
    "categoria": "PC",
    "numeroReviews": 20,
    "id": 49
  },
  {
    "imagen": "producto91.jpg",
    "nombre": "Tarjeta Gráfica RTX 3090",
    "descripcion": "Una tarjeta gráfica de alta gama con rendimiento excepcional para juegos y aplicaciones intensivas.",
    "precio": 1299.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 42,
    "id": 50
  },
  {
    "imagen": "producto92.jpg",
    "nombre": "SSD NVMe de 1TB",
    "descripcion": "Un SSD NVMe de 1TB para acelerar la velocidad de lectura/escritura y la carga del sistema.",
    "precio": 149.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 129.99,
    "categoria": "Partes PC",
    "numeroReviews": 35,
    "id": 51
  },
  {
    "imagen": "producto93.jpg",
    "nombre": "Procesador Ryzen 9 5900X",
    "descripcion": "Un procesador de alto rendimiento con múltiples núcleos y subprocesos para juegos y tareas intensivas.",
    "precio": 499.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 38,
    "id": 52
  },
  {
    "imagen": "producto94.jpg",
    "nombre": "Placa Base ATX Z590",
    "descripcion": "Una placa base ATX de alto rendimiento con capacidades de overclocking y múltiples puertos.",
    "precio": 199.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 179.99,
    "categoria": "Partes PC",
    "numeroReviews": 32,
    "id": 53
  },
  {
    "imagen": "producto95.jpg",
    "nombre": "Fuente de Alimentación 750W",
    "descripcion": "Una fuente de alimentación de 750W para garantizar un suministro de energía estable y confiable.",
    "precio": 89.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 26,
    "id": 54
  },
  {
    "imagen": "producto96.jpg",
    "nombre": "Memoria RAM DDR4 32GB",
    "descripcion": "Memoria RAM DDR4 de 32GB para un rendimiento óptimo en juegos y aplicaciones pesadas.",
    "precio": 249.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 219.99,
    "categoria": "Partes PC",
    "numeroReviews": 29,
    "id": 55
  },
  {
    "imagen": "producto97.jpg",
    "nombre": "Disco Duro HDD de 2TB",
    "descripcion": "Un disco duro HDD de gran capacidad para almacenar una gran cantidad de datos y juegos.",
    "precio": 79.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 23,
    "id": 56
  },
  {
    "imagen": "producto98.jpg",
    "nombre": "Caja de PC con Iluminación RGB",
    "descripcion": "Una caja de PC con iluminación RGB personalizable y espacio para una configuración de alto rendimiento.",
    "precio": 129.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 119.99,
    "categoria": "Partes PC",
    "numeroReviews": 31,
    "id": 57
  },
  {
    "imagen": "producto99.jpg",
    "nombre": "Ventiladores RGB para PC",
    "descripcion": "Ventiladores RGB con control de velocidad para mantener una temperatura óptima en tu PC.",
    "precio": 34.99,
    "descuento": false,
    "numeroEstrellas": 4.1,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 20,
    "id": 58
  },
  {
    "imagen": "producto101.jpg",
    "nombre": "Teclado Mecánico RGB",
    "descripcion": "Un teclado mecánico con retroiluminación RGB personalizable y teclas de respuesta rápida.",
    "precio": 89.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 79.99,
    "categoria": "Complementos",
    "numeroReviews": 24,
    "id": 59
  },
  {
    "imagen": "producto102.jpg",
    "nombre": "Auriculares Inalámbricos Gaming",
    "descripcion": "Auriculares inalámbricos diseñados para jugadores con sonido envolvente y micrófono con cancelación de ruido.",
    "precio": 69.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 19,
    "id": 60
  },
  {
    "imagen": "producto103.jpg",
    "nombre": "Mouse Gaming con Macros",
    "descripcion": "Un mouse gaming con botones programables para macros y sensor de alta precisión.",
    "precio": 54.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 49.99,
    "categoria": "Complementos",
    "numeroReviews": 16,
    "id": 61
  },
  {
    "imagen": "producto104.jpg",
    "nombre": "Alfombrilla de Ratón Grande",
    "descripcion": "Una alfombrilla de ratón extra grande con superficie suave para movimientos precisos.",
    "precio": 19.99,
    "descuento": false,
    "numeroEstrellas": 4.1,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 15,
    "id": 62
  },
  {
    "imagen": "producto105.jpg",
    "nombre": "Controlador de Juegos Inalámbrico",
    "descripcion": "Un controlador de juegos inalámbrico para jugar en PC y consolas con comodidad y precisión.",
    "precio": 39.99,
    "descuento": true,
    "numeroEstrellas": 4.0,
    "precioDescuento": 34.99,
    "categoria": "Complementos",
    "numeroReviews": 18,
    "id": 63
  },
  {
    "imagen": "producto106.jpg",
    "nombre": "Micrófono USB de Condensador",
    "descripcion": "Un micrófono de condensador USB de alta calidad para streaming y grabación de audio.",
    "precio": 69.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 22,
    "id": 64
  },
  {
    "imagen": "producto107.jpg",
    "nombre": "Hub USB de 7 Puertos",
    "descripcion": "Un hub USB de 7 puertos para expandir las conexiones de tu PC o laptop con facilidad.",
    "precio": 24.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 19.99,
    "categoria": "Complementos",
    "numeroReviews": 20,
    "id": 65
  },
  {
    "imagen": "producto108.jpg",
    "nombre": "Webcam Full HD 1080p",
    "descripcion": "Una webcam de alta definición con enfoque automático y cancelación de ruido para videoconferencias.",
    "precio": 59.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 27,
    "id": 66
  },
  {
    "imagen": "producto109.jpg",
    "nombre": "Mando a Distancia Universal",
    "descripcion": "Un mando a distancia universal para controlar todos tus dispositivos de entretenimiento.",
    "precio": 29.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 24.99,
    "categoria": "Complementos",
    "numeroReviews": 21,
    "id": 67
  },
  {
    "imagen": "producto110.jpg",
    "nombre": "Mesa para Gaming Ajustable",
    "descripcion": "Una mesa para gaming ajustable en altura y con soporte para monitor y accesorios.",
    "precio": 139.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 31,
    "id": 68
  },
]