export let productos = [
  {
      "imagen": "https://www.ktronix.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-197529985793-001.jpg?context=bWFzdGVyfGltYWdlc3wyMDc0NzR8aW1hZ2UvanBlZ3xhR1F6TDJneFppOHhNemt5TXpneU5EZzVNems0TWk4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TVRrM05USTVPVGcxTnprelh6QXdNUzVxY0djfGE1ZWQ1YWY0NjNjYmE1ZDUyZTIyY2I5OWJhNjZkODlmMTk3MDM3YWM2M2IwYjUzNjQ1YzU1NjA1ZjJiN2QyMzM",
      "nombre": "Laptop Gaming Modelo A",
      "descripcion": "Una potente laptop gaming con procesador de alta velocidad y gráficos impresionantes.",
      "stock": 22,
      "precio": 1099.99,
      "descuento": false,
      "numeroEstrellas": 4,
      "precioDescuento": 0,
      "categoria": "Laptop",
      "numeroReviews": 25,
      "id": 1,
      "comentarios": [
          {
              "nombre": "Juan",
              "comentario": "Excelente laptop, muy buena relación calidad-precio.",
              "estrellas": 5
          },
          {
              "nombre": "Pedro",
              "comentario": "La laptop es buena pero el servicio al cliente es pésimo.",
              "estrellas": 3
          },
          {
              "nombre": "María",
              "comentario": "La laptop es muy buena, la recomiendo.",
              "estrellas": 4
          },
          {
              "nombre": "Luis",
              "comentario": "La laptop me permite tener un gran rendimiento en mis juegos favoritos.",
              "estrellas": 4
          }
      ]
  },
  {
      "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_852127-MCO52213486516_102022-F.webp",
      "nombre": "Teclado Mecánico RGB",
      "descripcion": "Teclado mecánico con retroiluminación RGB personalizable para una experiencia de juego inmersiva.",
      "precio": 89.99,
      "descuento": true,
      "numeroEstrellas": 4.2,
      "precioDescuento": 69.99,
      "categoria": "Complementos",
      "numeroReviews": 18,
      "id": 2,
      "comentarios": [
        {
            "nombre": "Sofia Segura",
            "comentario": "El teclado es muy bueno, me encanta la iluminación RGB.",
            "estrellas": 5
        },
        {
            "nombre": "Manuel Figueroa",
            "comentario": "El teclado es bueno pero el servicio al cliente es pés",
            "estrellas": 3
        },
        {
            "nombre": "Ramirez Gonzales",
            "comentario": "El teclado es la mejor compra que he hecho en mucho tiempo.",
            "estrellas": 4
        },
        {
            "nombre": "Luis",
            "comentario": "El teclado me permite tener un gran rendimiento en mis juegos favoritos.",
            "estrellas": 4
        }
    ]
  },
  {
      "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_995599-MCO69058238316_042023-F.webp",
      "nombre": "Monitor Gaming 27 pulgadas",
      "descripcion": "Monitor de alta frecuencia de actualización y resolución para jugadores exigentes.",
      "precio": 349.99,
      "descuento": true,
      "numeroEstrellas": 4.6,
      "precioDescuento": 299.99,
      "categoria": "Monitor",
      "numeroReviews": 30,
      "id": 3,
      "comentarios": []
  },
  {
      "imagen": "https://i.linio.com/p/3c05933fd86a5915dfba97b35c11afad-product.webp",
      "nombre": "Tarjeta Gráfica GTX 3080",
      "descripcion": "Una tarjeta gráfica potente que ofrece un rendimiento de juego de última generación.",
      "precio": 799.99,
      "descuento": false,
      "numeroEstrellas": 4.8,
      "precioDescuento": 0,
      "categoria": "Partes PC",
      "numeroReviews": 40,
      "id": 4,
      "comentarios": [],
      "comentarios": []
  },
  {
      "imagen": "https://i.linio.com/p/f09aec3f09ae91525a13f6fcc738c915-product.webp",
      "nombre": "Auriculares Gaming Inalámbricos",
      "descripcion": "Auriculares inalámbricos con sonido envolvente para una experiencia de juego inmersiva.",
      "precio": 129.99,
      "descuento": false,
      "numeroEstrellas": 3,
      "precioDescuento": 0,
      "categoria": "Complementos",
      "numeroReviews": 22,
      "id": 5,
      "comentarios": []
  },
  {
      "imagen": "https://i.ebayimg.com/images/g/SsMAAOSwhDBfGF4w/s-l500.jpg",
      "nombre": "Silla Gaming Ergonómica",
      "descripcion": "Una silla ergonómica diseñada para sesiones de juego largas y cómodas.",
      "precio": 199.99,
      "descuento": true,
      "numeroEstrellas": 3,
      "precioDescuento": 169.99,
      "categoria": "Complementos",
      "numeroReviews": 28,
      "id": 6,
      "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/VdcAAOSwFq5kzjWF/s-l500.png",
    "nombre": "PC Gamer de Alto Rendimiento",
    "descripcion": "Una PC de alto rendimiento con procesador de última generación y tarjeta gráfica potente.",
    "precio": 1699.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 15,
    "id": 7,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_760989-MCO71275609389_082023-F.webp",
    "nombre": "Mouse Gaming con RGB",
    "descripcion": "Un mouse gaming con iluminación RGB personalizable y sensor de alta precisión.",
    "precio": 49.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 39.99,
    "categoria": "Complementos",
    "numeroReviews": 12,
    "id": 8,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_897288-MLA45260403198_032021-F.webp",
    "nombre": "Disco Duro SSD de 1TB",
    "descripcion": "Un disco duro SSD de gran capacidad para mejorar la velocidad y capacidad de almacenamiento de tu PC.",
    "precio": 129.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 23,
    "id": 9,
    "comentarios": []
  },
  {
    "imagen": "https://www.lenovo.com/medias/25198557406-G34w-30-20220726014906.png?context=bWFzdGVyfHJvb3R8MTE5NTUzfGltYWdlL3BuZ3xoMDYvaGU5LzE1Mjc3NjUyMzc3NjMwLnBuZ3w5NjU4ODhiNDAzYmYzMjdjNmYyNTAwMzQ3MzQzOTI3ZDU0YWFkNzI2ZWQ5NjE2MzM2Y2EzMmI3MDE5YTdmMjQ3",
    "nombre": "Monitor Curvo 32 pulgadas",
    "descripcion": "Un monitor curvo de gran tamaño con una inmersión visual impresionante para tus juegos.",
    "precio": 449.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 399.99,
    "categoria": "Monitor",
    "numeroReviews": 35,
    "id": 10,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_981977-MCO46914196855_072021-F.webp",
    "nombre": "Auriculares con Cancelación de Ruido",
    "descripcion": "Auriculares con tecnología de cancelación de ruido para una experiencia de juego sin distracciones.",
    "precio": 149.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Audio",
    "numeroReviews": 20,
    "id": 11,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_684963-MCO48221345438_112021-O.webp",
    "nombre": "Teclado Mecánico Compacto",
    "descripcion": "Un teclado mecánico compacto y portátil ideal para juegos en movimiento.",
    "precio": 79.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 69.99,
    "categoria": "Complementos",
    "numeroReviews": 14,
    "id": 12,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_722629-MLU71495580321_092023-F.webp",
    "nombre": "Laptop Gaming Modelo B",
    "descripcion": "Una laptop gaming de gama media con gráficos sólidos y rendimiento confiable.",
    "precio": 899.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 799.99,
    "categoria": "Laptop",
    "numeroReviews": 26,
    "id": 13,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRHqvpysqTwLI2931smSaPYKedEeCvIARCSX8GyZoIH0rwBi571IbKdMeUraNVdU0hKuOvxD3LzcUZWq3SG3Ba3oLvzcLkQAzSmw3VCkyw&usqp=CAE",
    "nombre": "Silla Gaming Estilo Racing",
    "descripcion": "Una silla estilo racing con diseño deportivo y soporte lumbar ajustable.",
    "precio": 169.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 19,
    "id": 14,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_838681-MLM43846583075_102020-F.webp",
    "nombre": "Placa Base para Gaming",
    "descripcion": "Una placa base diseñada para jugadores con múltiples puertos y capacidades de overclocking.",
    "precio": 129.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 109.99,
    "categoria": "Partes PC",
    "numeroReviews": 27,
    "id": 15,
    "comentarios": []
  },
  {
    "imagen": "https://i.linio.com/p/b2d8e7045b93178e3dc6904dbbd47f8a-product.webp",
    "nombre": "Mousepad Gaming Extra Grande",
    "descripcion": "Un mousepad extra grande para jugadores que necesitan mucho espacio para el ratón.",
    "precio": 19.99,
    "descuento": false,
    "numeroEstrellas": 4.0,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 16,
    "id": 16,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSlPIYN4GN5I_oABu4Kn9dtAwJH-4QT3ZIDetUmEG8O6-KgvUlR6GRnZAV7ibV0BRR_cXnEoYMCm8P2aXTYEtzM3vpkYV9H8tPYWsHdP6justFxHzilQ4yl&usqp=CAE",
    "nombre": "Memoria RAM DDR4 16GB",
    "descripcion": "Memoria RAM de alto rendimiento para mejorar la velocidad de tu PC.",
    "precio": 79.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 69.99,
    "categoria": "Partes PC",
    "numeroReviews": 22,
    "id": 17,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_639104-MCO72187520906_102023-F.webp",
    "nombre": "Sistema de Refrigeración Líquida",
    "descripcion": "Un sistema de refrigeración líquida eficiente para mantener tu PC fresco durante largas sesiones de juego.",
    "precio": 89.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 25,
    "id": 18,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/iZ4AAOSwdUhjAYXd/s-l500.png",
    "nombre": "Mochila para Portátil Gamer",
    "descripcion": "Una mochila resistente y espaciosa diseñada para transportar tu laptop gaming y accesorios.",
    "precio": 49.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 39.99,
    "categoria": "Complementos",
    "numeroReviews": 13,
    "id": 19,
    "comentarios": []
  },

  {
    "imagen": "https://i.linio.com/p/eaeadecee1384c5721708aaa59c75c8c-product.webp",
    "nombre": "Laptop Gamer Modelo C",
    "descripcion": "Una laptop gamer de alta gama con pantalla de alta frecuencia de actualización y gráficos excepcionales.",
    "precio": 1499.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 32,
    "id": 20,
    "comentarios": []
  },
  {
    "imagen": "https://i.linio.com/p/15abd3b04a64890369c931caa0697165-product.webp",
    "nombre": "Laptop Ultradelgada",
    "descripcion": "Una laptop ultradelgada y liviana ideal para jugadores en movimiento.",
    "precio": 999.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 899.99,
    "categoria": "Laptop",
    "numeroReviews": 22,
    "id": 21,
    "comentarios": []
  },
  {
    "imagen": "https://www.alkosto.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-4711121614538-001.jpg?context=bWFzdGVyfGltYWdlc3wyMTc1NDB8aW1hZ2UvanBlZ3xhR05oTDJoak15OHhNemczTmpBNU1UYzBPRE00TWk4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TkRjeE1URXlNVFl4TkRVek9GOHdNREV1YW5CbnwwZTcwMGE5Yjg2NmY2MzBlZGI3ZDYxYzI0Zjg0N2E2NzJkNDc4NzFiZDY5MWU3ZDU0NzcxMThiNzAzMjA4MTZh",
    "nombre": "Laptop de Gama Media",
    "descripcion": "Una laptop de gama media con rendimiento sólido y gráficos decentes para juegos.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 18,
    "id": 22,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_651093-MLU71266572179_082023-F.webp",
    "nombre": "Laptop Híbrida 2 en 1",
    "descripcion": "Una laptop híbrida con capacidad de convertirse en tableta para una versatilidad máxima.",
    "precio": 1199.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 1099.99,
    "categoria": "Laptop",
    "numeroReviews": 19,
    "id": 23,
    "comentarios": []
  },
  {
    "imagen": "https://www.alkosto.com/medias/750Wx750H-master-hotfolder-transfer-incoming-deposit-hybris-interfaces-IN-media-product-196800901132-001.jpg?context=bWFzdGVyfGltYWdlc3wyNTI1OTR8aW1hZ2UvanBlZ3xhREEzTDJnMk9DOHhNelUwTkRJNU1UY3lPVFF6T0M4M05UQlhlRGMxTUVoZmJXRnpkR1Z5TDJodmRHWnZiR1JsY2k5MGNtRnVjMlpsY2k5cGJtTnZiV2x1Wnk5a1pYQnZjMmwwTDJoNVluSnBjeTFwYm5SbGNtWmhZMlZ6TDBsT0wyMWxaR2xoTDNCeWIyUjFZM1F2TVRrMk9EQXdPVEF4TVRNeVh6QXdNUzVxY0djfDZmMmNhOTY1YWJlNTI1NjgwMjVlN2M1ZTQ4MjY1NjEyNzFkNzg5ZjdmNDY5YzUyYzUwNTUwMjVlMmYwMTkxYWI",
    "nombre": "Laptop de Edición de Video",
    "descripcion": "Una laptop potente diseñada para la edición de video y juegos de alto rendimiento.",
    "precio": 1799.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 28,
    "id": 24,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_962719-MLA53042953925_122022-F.webp",
    "nombre": "Laptop de Gama Alta",
    "descripcion": "Una laptop de gama alta con especificaciones de vanguardia para los jugadores más exigentes.",
    "precio": 2199.99,
    "descuento": true,
    "numeroEstrellas": 4.9,
    "precioDescuento": 1999.99,
    "categoria": "Laptop",
    "numeroReviews": 35,
    "id": 25,
    "comentarios": []
  },
  {
    "imagen": "https://i.linio.com/p/b926eebd64bc5897c92db5ccbf5270a6-product.webp",
    "nombre": "Laptop para Diseñadores Gráficos",
    "descripcion": "Una laptop diseñada para diseñadores gráficos y artistas digitales con pantalla de alta resolución.",
    "precio": 1399.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 29,
    "id": 26,
    "comentarios": []
  },
  {
    "imagen": "https://puntoscolombia.vtexassets.com/arquivos/ids/23516250-800-auto?v=638227265535030000&width=800&height=auto&aspect=true",
    "nombre": "Laptop Económica",
    "descripcion": "Una laptop económica ideal para jugadores principiantes con un presupuesto ajustado.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.1,
    "precioDescuento": 549.99,
    "categoria": "Laptop",
    "numeroReviews": 15,
    "id": 27,
    "comentarios": []
  },
  {
    "imagen": "https://i.linio.com/p/28a79e27ac8d318946ada27b9bae438c-product.webp",
    "nombre": "Laptop para Streaming",
    "descripcion": "Una laptop optimizada para transmisiones en vivo y contenido de video en línea.",
    "precio": 1299.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 1199.99,
    "categoria": "Laptop",
    "numeroReviews": 27,
    "id": 28,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_987978-MCO53373547477_012023-F.webp",
    "nombre": "Laptop para Programadores",
    "descripcion": "Una laptop diseñada para programadores y desarrolladores con rendimiento de alta velocidad.",
    "precio": 1099.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Laptop",
    "numeroReviews": 25,
    "id": 29,
    "comentarios": []
  },
  {
    "imagen": "https://s.alicdn.com/@sc04/kf/H8b0d1b18f6c5407fa68f6bab052d6148F.jpg_300x300.jpg",
    "nombre": "Monitor Curvo 34 pulgadas Ultra Ancho",
    "descripcion": "Un monitor curvo ultrapanorámico para una experiencia visual inmersiva como ninguna otra.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 38,
    "id": 30,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRlX6Q7r9ed2gzYWipqJZ1-xAg3CSIo16TCm_NX0q4zjDi99WCalDE2Tg-mliyZhsmpvmGnWxKYrrwqrTLzVc_8Lh2TGuUN&usqp=CAE",
    "nombre": "Monitor 4K HDR 27 pulgadas",
    "descripcion": "Un monitor 4K de alta resolución con soporte HDR para colores vibrantes y claridad impresionante.",
    "precio": 499.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 449.99,
    "categoria": "Monitor",
    "numeroReviews": 29,
    "id": 31,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRUAefVkPj3ZIZg1s52eVnZo2mwsbquIIqEjytWha6rqwaOAxNeO3_7qoaxSGiZnmOIwEgTiJ4Ohkfyitv5P1SeyXY6Evi-VXeLIz9g8AaXr3CbTNFuPYockQ&usqp=CAE",
    "nombre": "Monitor para Diseñadores Gráficos",
    "descripcion": "Un monitor de alta precisión diseñado para profesionales de diseño gráfico y edición de fotos.",
    "precio": 749.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 32,
    "id": 32,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSOvmmJF-QE4Uoaf4kcR1EmU6TNTUVBZjVN9F3PR9Zk60atD0PsADYy1tbpBVr6PRyoJzqDrjh3gR-4uVSL9-bgLCfrIH7Hzbm6oPk8yHE&usqp=CAE",
    "nombre": "Monitor 144Hz para Gaming",
    "descripcion": "Un monitor de alta frecuencia de actualización para jugadores competitivos que buscan la máxima suavidad.",
    "precio": 349.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 299.99,
    "categoria": "Monitor",
    "numeroReviews": 25,
    "id": 33,
    "comentarios": []
  },
  {
    "imagen": "https://www.lenovo.com/medias/06-Thinkvision-M14t-Hero-Front-Facing-Left.jpg?context=bWFzdGVyfHJvb3R8MTM1MDEzfGltYWdlL2pwZWd8aDM3L2g3NS8xMTgxMDQwODM5ODg3OC5qcGd8OTkwYzJiOGNjYTM3YjhhNjFlZDQ4ZjYxMjkxOTVkYTVlZWM2YmQ0NjA2M2E3M2QwOGZlMTA2M2ViMmY5MzBjZg",
    "nombre": "Monitor Tactil Multi Touch 14 pulgadas",
    "descripcion": "Un monitor táctil para interacciones intuitivas y aplicaciones educativas y creativas.",
    "precio": 199.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 18,
    "id": 34,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQU_qfT4LUk0A4scl-himUYSes5z_qtWOaLJqYKfzCgiw4Cnc4qkvKDPv-ONsU_B8lsbyO6zDw1EMu6xtzF8hNCLYNpobEF-XGMJd9p5JMIRjlOHUlBUo4raA&usqp=CAE",
    "nombre": "Monitor 32 pulgadas 4K Curvo",
    "descripcion": "Un monitor curvo de gran tamaño con resolución 4K para una experiencia visual asombrosa.",
    "precio": 699.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 599.99,
    "categoria": "Monitor",
    "numeroReviews": 28,
    "id": 35,
    "comentarios": []
  },
  {
    "imagen": "https://img01.huaweifile.com/sg/ms/co/pms/uomcdn/CO_HW_B2C/pms/202207/gbom/6941487224043/800_800_A666EB8A6B013D1D23BDA08812DFFA27mp.png",
    "nombre": "Monitor Gaming 24 pulgadas",
    "descripcion": "Un monitor gaming de 24 pulgadas con tiempo de respuesta ultrarrápido para jugadores competitivos.",
    "precio": 249.99,
    "descuento": false,
    "numeroEstrellas": 4.5,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 23,
    "id": 36,
    "comentarios": []
  },
  {
    "imagen": "https://www.bhphotovideo.com/cdn-cgi/image/format=auto,fit=scale-down,width=500,quality=95/https://www.bhphotovideo.com/images/images500x500/acer_um_je0aa_x02_32_curved_full_hd_1667817621_1734163.jpg",
    "nombre": "Monitor Curvo 27 pulgadas QHD",
    "descripcion": "Un monitor curvo de resolución QHD para una experiencia visual envolvente y nítida.",
    "precio": 399.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 349.99,
    "categoria": "Monitor",
    "numeroReviews": 21,
    "id": 37,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTqR7TbEqhPqDpCOJJQf4wVDRQCY-oIVirhLlT6sF920Oyj6vgJNVn6ebmJnWCJ_mjHYMdr6s4CSwtPre1m1_qxPEyIX9cC1i3Nf_fKZxDv&usqp=CAE",
    "nombre": "Monitor 23 pulgadas Full HD",
    "descripcion": "Un monitor Full HD de 23 pulgadas ideal para tareas de oficina y entretenimiento en casa.",
    "precio": 179.99,
    "descuento": false,
    "numeroEstrellas": 4.0,
    "precioDescuento": 0,
    "categoria": "Monitor",
    "numeroReviews": 15,
    "id": 38,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSjZpBBsP3VV-Qt1epE1fOnAFu6T7Eqj0iroB3KrTZUhyOgJHISaYegVC6jE4c94RnkSwaGMs6R544KkMoEOzYmCzlX3VKWCH-MNRY2JOBnc8RD3bESCT2neg&usqp=CAE",
    "nombre": "Monitor 27 pulgadas 4K IPS",
    "descripcion": "Un monitor de 27 pulgadas con panel IPS y resolución 4K para una calidad de imagen excepcional.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.3,
    "precioDescuento": 549.99,
    "categoria": "Monitor",
    "numeroReviews": 20,
    "id": 39,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_656768-MCO71861008603_092023-F.webp",
    "nombre": "PC Gaming de Alta Gama",
    "descripcion": "Una PC gaming de alta gama con procesador de última generación y tarjeta gráfica de alto rendimiento.",
    "precio": 1999.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 36,
    "id": 40,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRZ4DuY0S_vvKqdZIV47rfpPl6DmqkkhEIRkMF3ow_8eibk-NlkFvtbblEoOfp9j8hD5PDeSDrUjLHK4Fp7920HpSqonCcj5oj-XmP4RgmVVA5g906dP2V7mQ&usqp=CAE",
    "nombre": "Mini PC Compacto",
    "descripcion": "Un mini PC compacto y potente ideal para el entretenimiento en el hogar y tareas de oficina.",
    "precio": 599.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 549.99,
    "categoria": "PC",
    "numeroReviews": 19,
    "id": 41,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRp7C-JMj6_9A-BUoFBLdJghHEJEWnXZGA01BDvBr8shUsX8vVON5pLMQtsaLTv_WnT6juYcZ0YE83ffSM0gOrH632wJKBHZ3ITxjjsbKBBpkmQ-RDJtnvZ&usqp=CAE",
    "nombre": "PC de Oficina Profesional",
    "descripcion": "Una PC de oficina de alto rendimiento para tareas profesionales y multitarea eficiente.",
    "precio": 799.99,
    "descuento": false,
    "numeroEstrellas": 4.5,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 27,
    "id": 42,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT6FpRwvCGUp0y52W3NG92lRjCkrgK-0Ez8NOpBaB541jblb7p7j2Zyu5e3ufyxYT1vdprAkhjhbROZf7HTndQ8eKF_D8bM&usqp=CAE",
    "nombre": "PC Todo en Uno",
    "descripcion": "Un PC todo en uno con pantalla táctil y diseño elegante para espacios de trabajo modernos.",
    "precio": 1299.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 1199.99,
    "categoria": "PC",
    "numeroReviews": 32,
    "id": 43,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT8rdcj3E2-tHl6MVv9HccsgacgoKIniC6iyHGGRtcNWPictnfBNqsR3wjE1t3ZHWsK4Vn51vV9GhQ_UMkwMA6bJtx4c_7htXIdLeFpIws&usqp=CAE",
    "nombre": "PC de Juegos Compacto",
    "descripcion": "Un PC compacto diseñado para juegos de alto rendimiento en espacios reducidos.",
    "precio": 899.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 24,
    "id": 44,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_696542-MCO71102032643_082023-F.webp",
    "nombre": "PC de Diseño Gráfico",
    "descripcion": "Una PC de alto rendimiento diseñada para diseñadores gráficos y artistas digitales.",
    "precio": 1499.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 1399.99,
    "categoria": "PC",
    "numeroReviews": 30,
    "id": 45,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_833723-MCO50655936612_072022-F.webp",
    "nombre": "PC de Oficina Económica",
    "descripcion": "Una PC económica diseñada para tareas de oficina y navegación en Internet.",
    "precio": 499.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 17,
    "id": 46,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRqmchheKyQEwmaVgYrHqtBYZGR21-Ooa726_6V6ozBCwKnU7ihc-dTu9WOSq0aP3zVNua6PWoKbt4Bp8egnx4YyiZLACB_pVoCwhsRxAh5sE39ZgYh75D4&usqp=CAE",
    "nombre": "PC de Juegos de Gama Media",
    "descripcion": "Un PC de juegos de gama media con un equilibrio entre rendimiento y presupuesto.",
    "precio": 1199.99,
    "descuento": true,
    "numeroEstrellas": 4.4,
    "precioDescuento": 1099.99,
    "categoria": "PC",
    "numeroReviews": 28,
    "id": 47,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS-sOvFxVfMSxnbe0KKCkavvEhdo2sk5GYFlCtGTjNDBsfPcDqi3Apu-B45TVa38VTpyUAmVgAK82boFLFZZi3AlvTqrsvuaOG2xBCLurTYNt3vaBgtmXs1eQ&usqp=CAE",
    "nombre": "PC de Trabajo en Casa",
    "descripcion": "Una PC diseñada para el trabajo en casa y la teleconferencia con alta calidad de video y audio.",
    "precio": 699.99,
    "descuento": false,
    "numeroEstrellas": 4.6,
    "precioDescuento": 0,
    "categoria": "PC",
    "numeroReviews": 26,
    "id": 48,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQCiNPdjBUw8zsEZxdQz1Ewqvx4ofhTnkK_Bze6ll6YWPduxueNVz_lGccLLJBfoZrzOm3r7XEl35ebuVYSX3joujB34KWDk5C8zz0IaG0SDVCZ5_qlXSjikQ&usqp=CAE",
    "nombre": "PC de Juegos de Gama Baja",
    "descripcion": "Un PC de juegos de gama baja para juegos básicos y tareas de navegación.",
    "precio": 499.99,
    "descuento": true,
    "numeroEstrellas": 4.0,
    "precioDescuento": 449.99,
    "categoria": "PC",
    "numeroReviews": 20,
    "id": 49,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_905793-MCO71439627734_092023-F.webp",
    "nombre": "Tarjeta Gráfica RTX 3090",
    "descripcion": "Una tarjeta gráfica de alta gama con rendimiento excepcional para juegos y aplicaciones intensivas.",
    "precio": 1299.99,
    "descuento": false,
    "numeroEstrellas": 4.9,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 42,
    "id": 50,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTyrzxmSmTuL1bB6TZJ9lFyNy7nEAqtQBspuW0P6RyPFYAuAygEALfZG_ZYGb18MogZhpg82kbUHQVD-3nuo88GAuQxHaNI3Xm1GZDmLG35&usqp=CAE",
    "nombre": "SSD NVMe de 1TB",
    "descripcion": "Un SSD NVMe de 1TB para acelerar la velocidad de lectura/escritura y la carga del sistema.",
    "precio": 149.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 129.99,
    "categoria": "Partes PC",
    "numeroReviews": 35,
    "id": 51,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_894487-MLA53145808015_012023-F.webp",
    "nombre": "Procesador Ryzen 9 5900X",
    "descripcion": "Un procesador de alto rendimiento con múltiples núcleos y subprocesos para juegos y tareas intensivas.",
    "precio": 499.99,
    "descuento": false,
    "numeroEstrellas": 4.8,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 38,
    "id": 52,
    "comentarios": []
  },
  {
    "imagen": "https://www.empowerlaptop.com/wp-content/uploads/2019/04/Z170A-GAMING-7-1024x820.png",
    "nombre": "Placa Base ATX Z590",
    "descripcion": "Una placa base ATX de alto rendimiento con capacidades de overclocking y múltiples puertos.",
    "precio": 199.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 179.99,
    "categoria": "Partes PC",
    "numeroReviews": 32,
    "id": 53,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_917966-MLA46521140191_062021-F.webp",
    "nombre": "Fuente de Alimentación 750W",
    "descripcion": "Una fuente de alimentación de 750W para garantizar un suministro de energía estable y confiable.",
    "precio": 89.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 26,
    "id": 54,
    "comentarios": []
  },
  {
    "imagen": "https://down-co.img.susercontent.com/file/ph-11134201-23030-fi6brai9spov46",
    "nombre": "Memoria RAM DDR4 32GB",
    "descripcion": "Memoria RAM DDR4 de 32GB para un rendimiento óptimo en juegos y aplicaciones pesadas.",
    "precio": 249.99,
    "descuento": true,
    "numeroEstrellas": 4.7,
    "precioDescuento": 219.99,
    "categoria": "Partes PC",
    "numeroReviews": 29,
    "id": 55,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTgkfGJhu6FMviEkm-rG_lq5-1mYZo8v4E4R-ESS6LUiHCe98uVxjIti9B3bpHNraN7aZ2pkJBidtISF4RiaYQYbsUnxvWYiDoarD1b9Yu4as0b20A69J-m&usqp=CAE",
    "nombre": "Disco Duro HDD de 2TB",
    "descripcion": "Un disco duro HDD de gran capacidad para almacenar una gran cantidad de datos y juegos.",
    "precio": 79.99,
    "descuento": false,
    "numeroEstrellas": 4.2,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 23,
    "id": 56,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRQTOD6gNDp2CBXcEioh0o_OQylptCtpE9zFX7wjswXxbwhTDU-aN9qYOaeguTbvDxxvfh3qwwrGq61iG1blz7OjANqXGQo2X9UUi9DwipwpRavtPLS6Y4ZxU4&usqp=CAE",
    "nombre": "Caja de PC con Iluminación RGB",
    "descripcion": "Una caja de PC con iluminación RGB personalizable y espacio para una configuración de alto rendimiento.",
    "precio": 129.99,
    "descuento": true,
    "numeroEstrellas": 4.6,
    "precioDescuento": 119.99,
    "categoria": "Partes PC",
    "numeroReviews": 31,
    "id": 57,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRKwKRWTJpYUyo_OUAj7nCNEoW_dcygbvchGvvmcp_6utU0IVwL3f0OW20op8u_I8JyzMjwa-DWHvmD1GXQ6WOPj_wqEI4OGRH7YKXwHpAapfVx7pAB-q1c&usqp=CAE",
    "nombre": "Ventiladores RGB para PC",
    "descripcion": "Ventiladores RGB con control de velocidad para mantener una temperatura óptima en tu PC.",
    "precio": 34.99,
    "descuento": false,
    "numeroEstrellas": 4.1,
    "precioDescuento": 0,
    "categoria": "Partes PC",
    "numeroReviews": 20,
    "id": 58,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/yPoAAOSwI85j2uf3/s-l1600.jpg",
    "nombre": "Teclado Mecánico RGB",
    "descripcion": "Un teclado mecánico con retroiluminación RGB personalizable y teclas de respuesta rápida.",
    "precio": 89.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 79.99,
    "categoria": "Complementos",
    "numeroReviews": 24,
    "id": 59,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSZ_MScxgf17pLK6XGg5jC-RCaspj7tE7L92QTIiL9B9MgaYYKp_GGyi0yHEfwU4S5JpMpuQHJ4dGsGbAaF3rNkTMLFLKNhJsc6HfcWZHCsi_V6vd03ttD6-Q&usqp=CAE",
    "nombre": "Auriculares Inalámbricos Gaming",
    "descripcion": "Auriculares inalámbricos diseñados para jugadores con sonido envolvente y micrófono con cancelación de ruido.",
    "precio": 69.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 19,
    "id": 60,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/YukAAOSwc~Fjt94c/s-l500.jpg",
    "nombre": "Mouse Gaming con Macros",
    "descripcion": "Un mouse gaming con botones programables para macros y sensor de alta precisión.",
    "precio": 54.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 49.99,
    "categoria": "Complementos",
    "numeroReviews": 16,
    "id": 61,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_850987-MCO69644082410_052023-F.webp",
    "nombre": "Alfombrilla de Ratón Grande",
    "descripcion": "Una alfombrilla de ratón extra grande con superficie suave para movimientos precisos.",
    "precio": 19.99,
    "descuento": false,
    "numeroEstrellas": 4.1,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 15,
    "id": 62,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_961440-MCO72113058189_102023-F.webp",
    "nombre": "Controlador de Juegos Inalámbrico",
    "descripcion": "Un controlador de juegos inalámbrico para jugar en PC y consolas con comodidad y precisión.",
    "precio": 39.99,
    "descuento": true,
    "numeroEstrellas": 4.0,
    "precioDescuento": 34.99,
    "categoria": "Complementos",
    "numeroReviews": 18,
    "id": 63,
    "comentarios": []
  },
  {
    "imagen": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRjvL72KnKKCjFqrBhB1BOIhLeARCdpPhFWVcnfCvMuTJH7qEFJhdjXaePizQPMqEqHhyfeZqRezSmWdlWNX7RlUzZKqorpgWxb94kpl_y42igyp5O21D1BTA&usqp=CAE",
    "nombre": "Micrófono USB de Condensador",
    "descripcion": "Un micrófono de condensador USB de alta calidad para streaming y grabación de audio.",
    "precio": 69.99,
    "descuento": false,
    "numeroEstrellas": 4.3,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 22,
    "id": 64,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/k3sAAOSwcXllGx1o/s-l500.png",
    "nombre": "Hub USB de 7 Puertos",
    "descripcion": "Un hub USB de 7 puertos para expandir las conexiones de tu PC o laptop con facilidad.",
    "precio": 24.99,
    "descuento": true,
    "numeroEstrellas": 4.5,
    "precioDescuento": 19.99,
    "categoria": "Complementos",
    "numeroReviews": 20,
    "id": 65,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/Px0AAOSwcS9jsf7J/s-l500.jpg",
    "nombre": "Webcam Full HD 1080p",
    "descripcion": "Una webcam de alta definición con enfoque automático y cancelación de ruido para videoconferencias.",
    "precio": 59.99,
    "descuento": false,
    "numeroEstrellas": 4.4,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 27,
    "id": 66,
    "comentarios": []
  },
  {
    "imagen": "https://http2.mlstatic.com/D_NQ_NP_2X_669957-CBT53238956083_012023-F.webp",
    "nombre": "Mando a Distancia Universal",
    "descripcion": "Un mando a distancia universal para controlar todos tus dispositivos de entretenimiento.",
    "precio": 29.99,
    "descuento": true,
    "numeroEstrellas": 4.2,
    "precioDescuento": 24.99,
    "categoria": "Complementos",
    "numeroReviews": 21,
    "id": 67,
    "comentarios": []
  },
  {
    "imagen": "https://i.ebayimg.com/images/g/VykAAOSwOZxjEUwI/s-l500.png",
    "nombre": "Mesa para Gaming Ajustable",
    "descripcion": "Una mesa para gaming ajustable en altura y con soporte para monitor y accesorios.",
    "precio": 139.99,
    "descuento": false,
    "numeroEstrellas": 4.7,
    "precioDescuento": 0,
    "categoria": "Complementos",
    "numeroReviews": 31,
    "id": 68,
    "comentarios": []
  },
]